### ISSUE TITLE
App crashes on Android 7

### ISSUE THREAD

**Issue by stalniy** [CreativeSDK/phonegap-plugin-csdk-image-editor#28]
### Expected Behaviour
User is able to write over picture

### Actual Behaviour
When user clicks on "T" tool (for adding text over image) application crashes with this stack trace:
```java
java.lang.RuntimeException: Font asset not found assets/aviary/meme/LeagueGothic-Regular.otf
	at android.graphics.Typeface.createFromAsset(Typeface.java:206)
	at com.adobe.creativesdk.aviary.internal.headless.moa.MoaFontProxy.create(MoaFontProxy.java:102)
	at com.adobe.creativesdk.aviary.panels.TextPanel.onActivate(TextPanel.java:413)
	at com.adobe.creativesdk.aviary.panels.AbstractPanel.onActivate(AbstractPanel.java:523)
	at com.adobe.creativesdk.aviary.internal.AdobeImageEditorControllerAbstract.setCurrentState(AdobeImageEditorControllerAbstract.java:893)
	at com.adobe.creativesdk.aviary.internal.AdobeImageEditorControllerAbstract.access$000(AdobeImageEditorControllerAbstract.java:87)
	at com.adobe.creativesdk.aviary.internal.AdobeImageEditorControllerAbstract$1.onOpenEnd(AdobeImageEditorControllerAbstract.java:298)
	at com.adobe.creativesdk.aviary.widget.AdobeImageBottomBarAnimator.onAnimationCompleted(AdobeImageBottomBarAnimator.java:144)
	at it.sephiroth.android.library.viewrevealanimator.LollipopRevealAnimatorImpl$3.onAnimationEnd(LollipopRevealAnimatorImpl.java:157)
	at android.view.RenderNodeAnimator.onFinished(RenderNodeAnimator.java:381)
	at android.animation.RevealAnimator.onFinished(RevealAnimator.java:43)
	at android.view.RenderNodeAnimator.callOnFinished(RenderNodeAnimator.java:488)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

The same application works fine on Android 6

#### Steps to Reproduce
1. Open any cordova application on Anroid 7 with this plugin installed
2. click to edit image
3. choose "text" tool to add text over image

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android: 7.1.1
Android Build: N4F26T

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Manufacturer: Huawei
Model: Nexus 6P

#### PhoneGap CLI version and PhoneGap platform version
```sh
$ cordova --version
6.5.0

$ cordova platform version android
Installed platforms:
  android 6.1.2
```

#### Plugin version

phonegap-plugin-csdk-client-auth 1.0.6
phonegap-plugin-csdk-image-editor 1.0.0

**Comment by netzinkubator** [comment]
we are experiencing the same issue.
any news on it? was it fixed?

stacktrace:

java.lang.RuntimeException: Font asset not found assets/aviary/meme/LeagueGothic-Regular.otf
at android.graphics.Typeface.createFromAsset(Typeface.java:305)
at com.adobe.creativesdk.aviary.internal.headless.moa.MoaFontProxy.create(MoaFontProxy.java:102)

**Comment by lumiman** [comment]
I have the same issue, all Edit feature like crop, draw etc are fine but when try to add a text the app crashs

**Comment by pochubayk** [comment]
Also having the Same issue @macdonst @ashryanbeats and update on this issue?

**Comment by tuxes3** [comment]
same issue
