### ISSUE TITLE
Using stickers causes app to crash

### ISSUE THREAD

**Issue by macdonst** [CreativeSDK/phonegap-plugin-csdk-image-editor#9]
CSDK 0.9.1062

When I click on 

```
08-07 13:21:29.002  9439  9439 E AndroidRuntime: Process: io.cordova.hellocordova, PID: 9439
08-07 13:21:29.002  9439  9439 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at com.adobe.creativesdk.aviary.panels.StickersPanelAbstract.onLoadComplete(StickersPanelAbstract.java:190)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at com.adobe.creativesdk.aviary.panels.StickersPanelAbstract.onLoadComplete(StickersPanelAbstract.java:102)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.support.v4.content.Loader.deliverResult(Loader.java:126)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:154)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6077)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
08-07 13:21:29.002  9439  9439 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
08-07 13:21:29.004  4632  6876 W ActivityManager:   Force finishing activity io.cordova.hellocordova
```

Looking up through the logs I see:

```
08-07 13:29:21.354  9636 13650 W System.err: java.lang.IllegalArgumentException: Unknown URL content://io.cordova.hellocordova.CdsProvider/bulk/insertPackContentAndItems
08-07 13:29:21.354  9636 13650 W System.err:    at android.content.ContentResolver.bulkInsert(ContentResolver.java:1335)
08-07 13:29:21.354  9636 13650 W System.err:    at com.adobe.creativesdk.aviary.internal.cds.CdsManifestPacksConsumer.insertNewContentFromJson(CdsManifestPacksConsumer.java:538)
08-07 13:29:21.354  9636 13650 W System.err:    at com.adobe.creativesdk.aviary.internal.cds.CdsManifestPacksConsumer$2.run(CdsManifestPacksConsumer.java:269)
08-07 13:29:21.354  9636 13650 W System.err:    at com.adobe.creativesdk.aviary.internal.cds.CdsManifestPacksConsumer$2.run(CdsManifestPacksConsumer.java:255)
08-07 13:29:21.354  9636 13650 W System.err:    at com.adobe.creativesdk.aviary.internal.threading.ThreadPool$1.run(ThreadPool.java:76)
08-07 13:29:21.354  9636 13650 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-07 13:29:21.354  9636 13650 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-07 13:29:21.354  9636 13650 W System.err:    at java.lang.Thread.run(Thread.java:761)
08-07 13:29:21.354  9636 13650 W System.err:    at com.adobe.creativesdk.aviary.internal.threading.ThreadPool$LowPriorityThreadFactory$1.run(ThreadPool.java:265)
```

**Comment by macdonst** [comment]
My bad, the client auth plugin was not setting the application ID properly.
